#!/bin/bash
VERSION="198.3"
wget http://www.treedyn.org/download/treedynpack.tar.gz
tar -xzof treedynpack.tar.gz
mv treedynpack treednypack-${VERSION}
chmod 775 treedynpack-${VERSION}
ln -s treedynpack-${VERSION} treedyn
